version: "3.7"

services:
  postgres:
    image: postgres:15-bullseye
    hostname: pg
    container_name: sw2pg
    working_dir: /app
    user: "${PG_USER}:${PG_GROUP}"
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DATABASE}"
      - "PGUSER=${PG_USER}"
      - "PGPASSWORD=${PG_PASSWORD}"
      - "PGDATABASE=${PG_DATABASE}"
    volumes:
      - ./volumes/pg/home:/app
      - ./pg/initdb.${TARGET}:/docker-entrypoint-initdb.d
      - ./volumes/pg/data:/var/lib/postgresql/data
    networks:
      - local-network

  deno:
    build:
      context: api
      dockerfile: "Dockerfile"
      target: "${TARGET}"
    hostname: api
    container_name: sw2api
    working_dir: "/app"
    depends_on:
      - postgres
    environment:
      - "PORT=${API_PORT}"
      - "PG_USER=${PG_USER}"
      - "PG_PASSWORD=${PG_PASSWORD}"
      - "PG_SERVER=pg"
      - "PG_DATABASE=${PG_DATABASE}"
      - "PG_PORT=${PG_PORT}"
      - "TARGET=${TARGET}"
    ports:
      - "${API_EX_PORT}:${API_PORT}"
    volumes:
      - ./api:/app
      - ./volumes/deno-dir.${TARGET}:/deno-dir
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    name: sw2nw