version: "3.1"

services:
  postgres:
    image: postgres:15-bullseye
    hostname: pg
    container_name: sw2pg
    working_dir: /app
    user: "${UID}:${GID}"
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DATABASE}"
      - "PGUSER=${PG_USER}"
      - "PGPASSWORD=${PG_PASSWORD}"
      - "PGDATABASE=${PG_DATABASE}"
    volumes:
      - ./site/pg/data:/var/lib/postgresql/data
      - ./site/pg/initdb:/docker-entrypoint-initdb.d
      - ./site/pg/home:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - local-network

  nestjs:
    build: api
    hostname: api
    container_name: sw2api
    depends_on:
      - postgres
    user: "${UID}:${GID}"
    environment:
      - "PORT=${API_PORT}"
      - "PGUSER=${PG_USER}"
      - "PGPASSWORD=${PG_PASSWORD}"
      - "PGSERVER=pg"
      - "PGDATABASE=${PG_DATABASE}"
      - "PGPORT=${PG_PORT}"
    ports:
      - '${API_EX_PORT}:${API_PORT}'
    volumes:
      - ./api:/api
      - /app/node_modules
      - ./site/logs:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    name: sw2nw