################
# Tasks
################

### Get all tasks
GET http://localhost:8089/api/v1/tasks

### Delete task
DELETE http://localhost:8089/api/v1/tasks/03eb9b55-cf09-4c27-aafe-6c36ca0f0167

### Get task by ID
GET http://localhost:8089/api/v1/tasks/03eb9b55-cf09-4c27-aafe-6c36ca0f0167
