################
# Channels
################

### Get all Channels
GET http://localhost:8089/api/v1/channels

### Get Channel by ID
GET http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3

### Create Channel (1)
POST http://localhost:8089/api/v1/channels
Content-Type: application/json

{
    "name": "厚生労働省チャネル",
    "enabled": true
}

### Create Channel (0)
POST http://localhost:8089/api/v1/channels
Content-Type: text/plain

plain text

### Update Channel
PUT http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3
Content-Type: application/json

{
    "name": "厚生労働省チャネルRev2"
}

### Update Channel (disabled)
PUT http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3
Content-Type: application/json

{
    "enabled": true
}

### Update Channel (no content)
PUT http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3
Content-Type: application/json

{}

### Update Channel (plain text)
PUT http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3
Content-Type: text/plain

plain text

### Delete Channel
DELETE  http://localhost:8089/api/v1/channels/b3282836-d52c-452e-837f-cb842d09f5a3

