################
# Directories
################

### Create directory
POST http://localhost:18085/api/v1/directories
Content-Type: application/json

{
    "name": "armadillo"
}

### Get directory by ID
GET http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f

### Get all directories
GET http://localhost:18085/api/v1/directories

### Get sites by directory
GET http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f/sites

### Update directory
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "name": "armadillo2",
}

### Delete directory
DELETE  http://localhost:18085/api/v1/directories/189024c3-4eba-45b8-9a2d-80c04d1dd61e

################
# Metadata
################

### Create metadata
POST http://localhost:18085/api/v1/directories/a49149e7-ba0e-4a11-a47c-9b14c66ba021/metadata?key=type&value=list

### Get metadata
GET http://localhost:18085/api/v1/directories/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata?key=type

### Get all metadata
GET http://localhost:18085/api/v1/directories/a49149e7-ba0e-4a11-a47c-9b14c66ba021/metadata

### Delete metadata
DELETE  http://localhost:18085/api/v1/directories/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata?key=type

### Delete all metadata
DELETE  http://localhost:18085/api/v1/directories/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata