################
# Directories
################

### Get all directories
GET http://localhost:18085/api/v1/directories

### Get directory by ID
GET http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f

### Get directory by ID (not found)
GET http://localhost:18085/api/v1/directories/not-found

### Create directory (1)
POST http://localhost:18085/api/v1/directories
Content-Type: application/json

{
    "name": "内閣官房",
    "metadata": {
        "type": "list"
    },
    "enabled": "true"
}

### Create directory (metadata, stringified json)
POST http://localhost:18085/api/v1/directories
Content-Type: application/json

{
    "name": "内閣官房",
    "metadata": "{ \"type\": \"list\" }",
    "enabled": true
}

### Create directory (metadata, not json)
POST http://localhost:18085/api/v1/directories
Content-Type: application/json

{
    "name": "内閣官房",
    "metadata": "type: list",
    "enabled": true
}

### Create directory (not json)
POST http://localhost:18085/api/v1/directories
Content-Type: text/plain

plain text

### Update directory
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "name": "内閣官房：会議"
}

### Update directory (metadata)
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "metadata": {
        "type": "list"
    }
}

### Update directory (metadata, stringified json)
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "metadata": "{ \"type\": \"list\" }"
}

### Update directory (metadata, not json)
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "metadata": "type: list"
}

### Update directory (disabled)
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "enabled": false
}

### Update directory (no content)
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{}

### Update directory (plain text)
PUT http://localhost:18085/api/v1/directories/dfe4965a-9d2c-4cd5-8a0a-3541eeb4b54b
Content-Type: text/plain

plain text

### Update directory (not found)
PUT  http://localhost:18085/api/v1/directories/not-found

### Delete directory
DELETE  http://localhost:18085/api/v1/directories/a87ac4e7-f896-472e-9c04-86bba02abcaf

### Delete directory (not found)
DELETE  http://localhost:18085/api/v1/directories/not-found

################
# Metadata
################

### Get all metadata by directory ID
GET http://localhost:18085/api/v1/directories/d43e6d85-e0e8-4b01-ad9e-2926db994c5e/metadata

### Get metadata by directory ID and key
GET http://localhost:18085/api/v1/directories/d43e6d85-e0e8-4b01-ad9e-2926db994c5e/metadata/type

### Create metadata
POST http://localhost:18085/api/v1/directories/d43e6d85-e0e8-4b01-ad9e-2926db994c5e/metadata
Content-Type: application/json

{
    "type": "list"
}

### Update metadata
PUT http://localhost:18085/api/v1/directories/d43e6d85-e0e8-4b01-ad9e-2926db994c5e/metadata
Content-Type: application/json

{
    "type": "List"
}

### Delete directory
DELETE  http://localhost:18085/api/v1/directories/d43e6d85-e0e8-4b01-ad9e-2926db994c5e/metadata/type