################
# Directories
################

### Create directory
POST http://localhost:18085/api/v1/directories
Content-Type: application/json

{
    "name": "armadillo",
    "enabled": true
}

### Get directory by ID
GET http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f

### Get all directories
GET http://localhost:18085/api/v1/directories

### Update directory
PUT http://localhost:18085/api/v1/directories/ae8ac08c-2f3e-41b5-8f70-db13b3d4b12f
Content-Type: application/json

{
    "name": "armadillo2",
}

### Delete directory
DELETE  http://localhost:18085/api/v1/directories/189024c3-4eba-45b8-9a2d-80c04d1dd61e

################
# Metadata
################

### Create metadata
POST http://localhost:18085/api/v1/directories/189024c3-4eba-45b8-9a2d-80c04d1dd61e/metadata
Content-Type: application/json

{
    "type": "list",
    "state": "active"
}

### Get metadata
GET http://localhost:18085/api/v1/directories/375395e0-dc12-49c4-9b52-eaee3cc3af44/metadata/type

### Get all metadata
GET http://localhost:18085/api/v1/directories/e463d1cf-feb6-45d4-a19d-7389ca34a14d/metadata

### Update metadata
PUT http://localhost:18085/api/v1/directories/375395e0-dc12-49c4-9b52-eaee3cc3af44/metadata
Content-Type: application/json

{
    "type": "List"
}

### Delete metadata
DELETE  http://localhost:18085/api/v1/directories/375395e0-dc12-49c4-9b52-eaee3cc3af44/metadata/type

### Delete all metadata
DELETE  http://localhost:18085/api/v1/directories/375395e0-dc12-49c4-9b52-eaee3cc3af44/metadata

### Create metadata for all directories
POST http://localhost:18085/api/v1/directories/metadata
Content-Type: application/json

{
    "lock": "locked"
}

### Get metadata for all directories
GET http://localhost:18085/api/v1/directories/metadata/state

### Update metadata for all directories
PUT http://localhost:18085/api/v1/directories/metadata?name=chicken2&strict=true
Content-Type: application/json

{
    "lock": "unlocked",
    "state": "superactive"
}

### Delete metadata for all directories
DELETE  http://localhost:18085/api/v1/directories/metadata/state