################
# Sites
################

### Get all Sites
GET http://localhost:18085/api/v1/sites

### Get Site by ID
GET http://localhost:18085/api/v1/sites/2ecb3609-fadb-4320-8764-b10e8ae9f912

### Create Site (1)
POST http://localhost:18085/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.mhlw.go.jp/stf/new-info/",
    "name": "厚生労働省新着情報",
    "directory": "89bf38fd-7fe0-42af-aab0-3348e0675cda"
}

### Create Site (2)
POST http://localhost:18085/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.meti.go.jp/shingikai/index_report.html",
    "name": "経済産業省報告",
    "directory": "e88d7483-f988-46ac-873f-0e4b71c6c979"
}

### Create Site (0)
POST http://localhost:18085/api/v1/sites
Content-Type: text/plain

plain text

### Update Site
PUT http://localhost:18085/api/v1/sites/3364fa54-5d12-4c5f-b428-bc8e8eebaab0
Content-Type: application/json

{
    "name": "厚生労働省Rev2",
    "directory": "769c2f96-4b28-4d05-97db-9c47f460eb6f",
}

### Update Site (no content)
PUT http://localhost:18085/api/v1/sites/de876013-33df-47bb-ae2c-154faaf63d80
Content-Type: application/json

{}

### Update Site (plain text)
PUT http://localhost:18085/api/v1/sites/de876013-33df-47bb-ae2c-154faaf63d80
Content-Type: text/plain

plain text

### Delete Site
DELETE  http://localhost:18085/api/v1/sites/63821c73-8edf-41f8-b63d-299912060d6c

################
# Reosurces
################

POST http://localhost:18085/api/v1/sites/9c11eefc-b4d8-49be-b3f3-58911b354fc4/resources
Content-Type: application/json

{
    "uri": "https://www.mhlw.go.jp/hoge/",
    "name": "厚生労働省HOGE情報",
    "properties": {
        "title": "HOGE情報",
        "reason": "new"
    }
}

################
# Metadata
################

### Create metadata
POST http://localhost:18085/api/v1/sites/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata?key=type&value=list

### Get metadata
GET http://localhost:18085/api/v1/sites/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata?key=type

### Get all metadata
GET http://localhost:18085/api/v1/sites/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata

### Delete metadata
DELETE  http://localhost:18085/api/v1/sites/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata?key=type

### Delete all metadata
DELETE  http://localhost:18085/api/v1/sites/b2f39c24-1fed-49d4-89c3-7a5b7279c39f/metadata