### Get all Sites
GET http://localhost:8089/api/v1/sites

### Get Site by ID
GET http://localhost:8089/api/v1/sites/1

### Create Site (1)
POST http://localhost:8089/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.mhlw.go.jp/stf/shingi/indexshingi.html",
    "name": "厚生労働省：審議会・研究会等",
    "type": "html:list",
    "enabled": true
}

### Create Site (2)
POST http://localhost:8089/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.nedo.go.jp/search/index.php?type=koubo",
    "name": "NEDO公募情報②",
    "type": "html",
    "enabled": true
}

### Update Site
PUT http://localhost:8089/api/v1/sites/5
Content-Type: application/json

{
    "uri": "https://www.nedo.go.jp/search/index.php?type=koubo",
    "name": "NEDO:公募情報②Rev1",
    "type": "html",
    "enabled": true
}

### Update Site (partial data)
PUT http://localhost:8089/api/v1/sites/5
Content-Type: application/json

{
    "name": "NEDO:公募情報②Rev2"
}

### Update Site (disabled)
PUT http://localhost:8089/api/v1/sites/1
Content-Type: application/json

{
    "enabled": false
}

### Delete Site
DELETE  http://localhost:8089/api/v1/sites/7

### Get Site Resources by ID
GET http://localhost:8089/api/v1/sites/11/resources

### Update Site Resources by ID
PUT http://localhost:8089/api/v1/sites/11/resources

### Delete Site Resources by ID
DELETE http://localhost:8089/api/v1/sites/11/resources