### Get all Sites
GET http://localhost:8089/api/v1/sites

### Get Site by ID
GET http://localhost:8089/api/v1/sites/1

### Create Site (1)
POST http://localhost:8089/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.mhlw.go.jp/stf/shingi/indexshingi.html",
    "name": "厚生労働省：審議会・研究会等",
    "type": "html:list",
    "enabled": true
}

### Create Site (2)
POST http://localhost:8089/api/v1/sites
Content-Type: application/json

{
    "uri": "https://www.meti.go.jp/shingikai/index_report.html",
    "name": "経済産業省：報告書",
    "type": "html",
    "enabled": true
}

### Create Site (0)
POST http://localhost:8089/api/v1/sites
Content-Type: text/plain

plain text

### Update Site
PUT http://localhost:8089/api/v1/sites/2
Content-Type: application/json

{
    "name": "経済産業省：報告書Rev2"
}

### Update Site (disabled)
PUT http://localhost:8089/api/v1/sites/1
Content-Type: application/json

{
    "enabled": false
}

### Update Site (no content)
PUT http://localhost:8089/api/v1/sites/1
Content-Type: application/json

{}

### Update Site (plain text)
PUT http://localhost:8089/api/v1/sites/1
Content-Type: text/plain

plain text

### Delete Site
DELETE  http://localhost:8089/api/v1/sites/2

### Get Site Resources by ID
GET http://localhost:8089/api/v1/sites/2/resources

### Update Site Resources by ID
PUT http://localhost:8089/api/v1/sites/2/resources

### Delete Site Resources by ID
DELETE http://localhost:8089/api/v1/sites/2/resources